"""empty message

Revision ID: 74bf2c99b9f1
Revises: 20362c961ec7
Create Date: 2023-10-12 03:03:20.972222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bf2c99b9f1'
down_revision = '20362c961ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.Column('skin_color', sa.String(length=100), nullable=True),
    sa.Column('eye_color', sa.String(length=100), nullable=True),
    sa.Column('Birth_Year', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('skin_color', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Birth_Year', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='character_pkey')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
